# Generated by Django 4.1.7 on 2023-03-03 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=18)),
                ('location', models.URLField()),
                ('information', models.TextField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Hostel',
                'verbose_name_plural': 'Hostels',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('price', models.IntegerField()),
                ('room_type', models.CharField(choices=[('duo_room', 'Duo Room'), ('squad_room', 'Squad Room')], max_length=13)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
