# Generated by Django 4.1.7 on 2023-02-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='information',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='phone',
            field=models.CharField(max_length=18),
        ),
    ]
