# Generated by Django 4.1.7 on 2023-02-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_hostel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
