# Generated by Django 4.1.7 on 2023-02-26 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hostels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=8
                    ),
                ),
                (
                    "faculty",
                    models.CharField(
                        choices=[
                            ("FKPI", "FKPI"),
                            ("NKLP", "NKLP"),
                            ("FPK", "FPK"),
                            ("FRDCP", "FRDCP"),
                        ],
                        max_length=8,
                    ),
                ),
                ("everage_score", models.IntegerField(null=True)),
                ("payment_status", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "room_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hostels.room",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
